Web/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Mời bạn nhập tên tài khoản")]
        public string Username { set; get; }
        [Required(ErrorMessage = "Mời bạn nhập mật khẩu")]
        public string Password { set; get; }
        public bool Rememberme { set; get; }
    }
}

Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web;
using Web.Models;
using Web.DAO;
using Web.Core;
using Web.Commons;
using Web.Model;
using System.Web.Script.Serialization;

namespace Web.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        //public ActionResult Login(Login lg)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var dao = new login();
        //        var result = dao.Login(lg.Username, HelperEncryptor.Md5Hash(lg.Password));
        //        if (result == 1)
        //        {
        //            var user = dao.GetById(lg.Username);
        //            var userSession = new UserLogin();
        //            Session["name"] = user.UserName;
        //            Session["id"] = user.ID;
        //            userSession.Username = user.UserName;
        //            userSession.UserID = user.ID;
        //            Session.Add(CommonConstant.USER_SESSION, userSession);
        //            return RedirectToAction("Index", "Home");
        //        }
        //        else if (result == 0)
        //        {
        //            ModelState.AddModelError("", "Tài khoản không đúng");
        //        }
        //        else if (result == -1)
        //        {
        //            ModelState.AddModelError("", "Tài khoản đang bị khóa");
        //        }
        //        else if (result == -2)
        //        {
        //            ModelState.AddModelError("", "Mật khẩu không đúng");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "Đăng nhập không thành công");
        //        }
        //    }
        //    return View("Index");
        //}
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        public JsonResult Register(string id)
        {
            LedQuaTangEntities db = new LedQuaTangEntities();
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            User u = serializer.Deserialize<User>(id);
            u.CreatedDate = DateTime.Now;
            db.Users.Add(u);
            return Json(new
            {

            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Logins(string id, string user, string pass)
        {
            LedQuaTangEntities db = new LedQuaTangEntities();
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            User u = serializer.Deserialize<User>(id);
            Session["id"] = "";
            var dao = new login();
            var result = dao.Login(user, HelperEncryptor.Md5Hash(pass));
            var userr = dao.GetById(user, HelperEncryptor.Md5Hash(pass));
            if (userr != null)
            {
                
                Session["name"] = userr.UserName;
                Session["id"] = userr.ID;
                var userSession = new UserLogin();
                userSession.Username = userr.UserName;
                userSession.UserID = userr.ID;
                Session.Add(CommonConstant.USER_SESSION, userSession);
            }

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckAlready(string userrg)
        {
            LedQuaTangEntities db = new LedQuaTangEntities();
            var check = db.Users.FirstOrDefault(x => x.UserName == userrg);
            if (check != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

    }
}

Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using Web.BaseSecurity;
using Web.Core;
using Web.Model;
using Web.Model.CustomModel;
using Web.Repository;
using Web.Repository.Entity;

namespace Web.Controllers
{
    public class UserController : BaseController
    {
        //
        // GET: /Login/
        private readonly IUserRepository _userRepository = new UserRepository();
        private LedQuaTangEntities dbcontext = new LedQuaTangEntities();
        public ActionResult LogIn()
        {
            if (User != null) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(User obj)
        {
            if (string.IsNullOrEmpty(obj.UserName) || string.IsNullOrWhiteSpace(obj.Password))
            {
                Session["Messenger"] = new Notified
                {
                    Value = EnumNotifield.Error,
                    Messenger = "Bạn chưa nhập tên đăng nhập hoặc mật khẩu nhập vào không đúng!"
                };
                return View();
            }
            var user =
                _userRepository.GetAll()
                    .FirstOrDefault(
                        u => u.Password == HelperEncryptor.Md5Hash(obj.Password) && u.UserName == obj.UserName);
            if (user != null)
            {
                if (user.Active == true)
                {
                    _userRepository.Edit(user);
                    if (user.Active == false)
                    {
                        Session["Messenger"] = "Tài khoản này chưa được kích hoạt!";
                        return View();
                    }
                    var serializeModel = new CustomPrincipalSerializeModel
                    {
                        ID = user.ID,
                        Username = user.UserName,
                        FullName = user.FullName,
                        Email = user.Email,
                        UserType = user.UserType,
                    };
                    var serializer = new JavaScriptSerializer();
                    var userData = serializer.Serialize(serializeModel);
                    var authTicket = new FormsAuthenticationTicket(
                        1,
                        obj.UserName,
                        DateTime.Now,
                        DateTime.Now.AddHours(1),
                        false,
                        userData);

                    var encTicket = FormsAuthentication.Encrypt(authTicket);
                    var faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
                    Response.Cookies.Add(faCookie);
                }
                else
                {
                    Session["Messenger"] = "Tài Khoản chưa được kích hoạt";
                    return View();
                }
            }
            else
            {
                Session["Messenger"] = "Tên đăng nhập hoặc mật khẩu không đúng!";
                return View();
            }
            var preUrl = (Uri)Session["returnUrl"];
            if (preUrl != null)
            {
                Session["returnUrl"] = null;
                return Redirect(preUrl.ToString());
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(User user)
        {
            user.CreatedDate = DateTime.Now;
            user.Active = false;
            user.Password = HelperEncryptor.Md5Hash(user.Password);
            var arrUserName = _userRepository.GetAll().Select(g => g.UserName);
            if (arrUserName.Contains(user.UserName))
            {
                ViewBag.existUser = 1;
                return View();
            }
            _userRepository.Add(user);
            return Redirect("/?regsuccess=1");
        }
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassword(string Email)
        {
            var arrEmail = _userRepository.GetAll().Select(g => g.Email);
            if (!arrEmail.Contains(Email))
            {
                ViewBag.noEmail = 1;
                return View();
            }
            return Redirect("/?resetpass=1");
        }
        #region Đăng nhập rồi 
        [Authorize]
        public ActionResult Edit()
        {
           
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit(User user)
        {
            var userold = _userRepository.Find(User.ID);
            userold.FullName = user.FullName;
            userold.Phone = user.Phone;
            userold.Address = user.Address;
            userold.DonviId = user.DonviId;
            userold.ChucVuId = user.ChucVuId;
            _userRepository.Edit(userold);
            return Redirect("/?success=1");
        }
        [Authorize]
        public ActionResult ChangePass()
        {
            var id = User.ID;
            if (id < 1)
            {
                return Redirect("/Error/AccessDenined");
            }
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult ChangePass(User user)
        {
            var id = User.ID;
            if (id < 1)
            {
                return Redirect("/Error/AccessDenined");
            }
            var userold = _userRepository.Find(id);
            var passnew = HelperEncryptor.Md5Hash(user.Password);
            if (passnew != userold.Password)
            {
                ViewBag.wrongpass = 1;
                return View();
            }
            var newpassword = Request["NewPassword"];
            if (!string.IsNullOrEmpty(newpassword))
            {
                var passcut = HelperEncryptor.Md5Hash(newpassword);
                userold.Password = passcut;
                _userRepository.Edit(userold);
            }
            return Redirect("/?success=1");
        }
        #endregion
        public ActionResult Profiled()
        {
            return View();
        }
        public JsonResult Getdetail(int id)
        {
            var user = dbcontext.Users.Find(id);
            var gd = user.Gender;
            return Json(new
            {
                data = user,
                gender = gd
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(string id)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            User u = serializer.Deserialize<User>(id);
            
            if (u.ID != 0)
            {
                var user = dbcontext.Users.Find(u.ID);
                user.FullName = u.FullName;
                user.Email = u.Email;
                user.Phone = u.Phone;
                user.Gender = u.Gender;
                user.Birthday = u.Birthday;
                dbcontext.SaveChanges();
            }
            return Json(new
            {
                data = u
            }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Web/Views/User/ChangePass.cshtml
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
}
@using Web.Areas.Admin.Controllers
@model Web.Model.tbl_User
<script src="/Scripts/jquery.validate.min.js"></script>
<div class="panel panel-color panel-primary panel-pages" style="box-shadow: 1px 30px 48px 5px rgba(142, 142, 142, 0.71); ">
    <div class="panel-heading bg-img toplogin" style="background-color:#09699c !important">
        <img src="~/Content/Admin/images/logo.png" />
       
        <h3 class="text-center m-t-10 text-white">@ConfigTextController.GetValueCFT("hmenu_changepass") <br> @ConfigTextController.GetValueCFT("login_title")</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("ChangePass", "User", FormMethod.Post, new { id = "frmDKThanhVien", @class = "form-horizontal" }))
        {
            if (ViewBag.wrongpass == 1)
            {
                <div class="form-group">
                    <div class="col-xs-12 text-danger">@ConfigTextController.GetValueCFT("wrongpass")</div>
                </div>
            }
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.PasswordFor(g => g.Password, new { @class = "form-control input-lg", required = "", placeholder = @ConfigTextController.GetValueCFT("oldpass") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.Password("NewPassword","", new { @class = "form-control input-lg", required = "", placeholder = @ConfigTextController.GetValueCFT("newpass") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.Password("ReNewPassword","", new { @class = "form-control input-lg", required = "", placeholder = @ConfigTextController.GetValueCFT("resetnewpass") })
                </div>
            </div>
            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <button class="btn btn-primary waves-effect waves-light btn-lg w-lg" type="submit">@ConfigTextController.GetValueCFT("hmenu_changepass")</button>
                </div>
            </div>
        }
    </div>
</div>
<script>
    // Basic Form
    $(document).ready(function () {
        $("#frmDKThanhVien").validate({
            rules:
            {
                Password:
                {
                    required: true,
                    minlength: 6,
                },
                NewPassword:
                {
                    required: true,
                    minlength: 6,
                },
                ReNewPassword:
                {
                    required: true,
                    minlength: 6,
                    equalTo: "#NewPassword"
                }
            },
            messages:
            {
                Password:
                {
                    required: "@ConfigTextController.GetValueCFT("pass_validpass")",
                    minlength: "@ConfigTextController.GetValueCFT("pass_minlength")"
                },
                NewPassword:
                {
                    required: "@ConfigTextController.GetValueCFT("pass_validnew")",
                    minlength: "@ConfigTextController.GetValueCFT("pass_minlength")",
                   
                },
                ReNewPassword:
                {
                    required: "@ConfigTextController.GetValueCFT("pass_validrenew")",
                    minlength: "@ConfigTextController.GetValueCFT("pass_minlength")",
                    equalTo: "@ConfigTextController.GetValueCFT("pass_validequal")"
                },
            }
        });
    });
</script>
<style>
    label{font-weight:normal}
</style>

Web/Views/User/Edit.cshtml
@using Web.Model;
@using Web.Areas.Admin.Controllers
@{
    ViewBag.Title = "Cập nhật thông tin";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
    var lstdonvi = (List<tbl_DMChung>)TempData["donvi"];
    lstdonvi.ForEach(g => g.Ten = string.Concat(Enumerable.Repeat("--", g.Level)) + " " + g.Ten);
    var lstchucvu = (List<tbl_ChucVu>)TempData["chucvu"];
}
@model Web.Model.tbl_User
<script src="/Scripts/jquery.validate.min.js"></script>
<div class="panel panel-color panel-primary panel-pages" style="box-shadow: 1px 30px 48px 5px rgba(142, 142, 142, 0.71); ">
    <div class="panel-heading bg-img toplogin">
        <img src="/Content/Admin/images/logo.png" />
        <h3 class="text-center m-t-10 text-white">@ConfigTextController.GetValueCFT("user_edit") <br> @ConfigTextController.GetValueCFT("login_title")</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "User", FormMethod.Post, new { id = "frmDKThanhVien", @class = "form-horizontal" }))
        {
            <div class="form-group ">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("tendangnhap"): </b>@Model.UserName</div>
            </div>
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("lienhe_email"): </b>@Model.Email</div>
            </div>
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("lienhe_hovaten")</b></div>
                <div class="col-xs-12">
                    @Html.TextBoxFor(g=>g.FullName, new {@class="form-control input-lg", placeholder= @ConfigTextController.GetValueCFT("lienhe_hovaten") })
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("cd_diachi")</b></div>
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Address, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("cd_diachi") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("cd_tendonvi")</b></div>
                <div class="col-xs-12">
                    @Html.DropDownListFor(x => x.DonviId, new SelectList(lstdonvi, "Id", "Ten"), "--"+@ConfigTextController.GetValueCFT("cd_tendonvi")+"--", new { @class = "form-control input-lg" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("register_chucvu")</b></div>
                <div class="col-xs-12">
                    @Html.DropDownListFor(x => x.ChucVuId, new SelectList(lstchucvu, "ID", "Name"), "--"+ @ConfigTextController.GetValueCFT("register_chucvu") + "--", new { @class = "form-control input-lg" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("register_dtban")</b></div>
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Telephone, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("register_dtban") })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-xs-12"><b>@ConfigTextController.GetValueCFT("register_sodd")</b></div>
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Phone, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("register_sodd") })
                </div>
            </div>
            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <button class="btn btn-primary waves-effect waves-light btn-lg w-lg" type="submit">@ConfigTextController.GetValueCFT("edit")</button>
                </div>
            </div>
        }
    </div>
</div>
<script>
    // Basic Form
    $(document).ready(function () {
        $("#frmDKThanhVien").validate({
            rules:
            {
                FullName:
                {
                    required: true
                },
            },
            messages:
            {
                FullName:
                {
                    required: "@ConfigTextController.GetValueCFT("edit_validatehoten")"
                }
            }
        });
    });
</script>
<style>
    label{font-weight:normal}
</style>

Web/Views/User/ForgotPassword.cshtml
@{
    ViewBag.Title = "Khôi phục mật khẩu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
}
@model Web.Model.tbl_User
<script src="/Scripts/jquery.validate.min.js"></script>
<div class="panel panel-color panel-primary panel-pages" style="box-shadow: 1px 30px 48px 5px rgba(142, 142, 142, 0.71); ">
    <div class="panel-heading bg-img toplogin">
        <img src="/Content/Admin/images/logo.png" />
        <h3 class="text-center m-t-10 text-white">Khôi phục mật khẩu <br> Liên minh HTX Quảng Trị</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("ForgotPassword", "User", FormMethod.Post, new { id = "frmDKThanhVien", @class = "form-horizontal" }))
        {
            if (ViewBag.noEmail == 1)
            {
                <div class="form-group">
                    <div class="col-xs-12 text-danger">Email không tồn tại !</div>
                </div>
            }
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g=>g.Email, new {@class="form-control input-lg", type="email", required="", placeholder="Email"})
                </div>
            </div>
            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <button class="btn btn-primary waves-effect waves-light btn-lg w-lg" type="submit">Hoàn tất</button>
                </div>
            </div>

            <div class="form-group m-t-30">
                <div class="col-sm-12 text-center">
                    @Html.ActionLink("Đã có tài khoản?","Login")
                </div>
            </div>
        }
    </div>
</div>
<script>
    // Basic Form
    $(document).ready(function () {
        $("#frmDKThanhVien").validate({
            rules:
            {
                Email:
                {
                    email: true,
                    required: true
                }
            },
            messages:
            {
                Email:
                {
                    email: "Email không đúng định dạng",
                    required: "Chưa nhập email"
                }
            }
        });
    });
</script>
<style>
    label{font-weight:normal}
</style>

Web/Views/User/Register.cshtml
@using Web.Model;
@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
    var lstdonvi = (List<tbl_DMChung>)TempData["donvi"];
    lstdonvi.ForEach(g => g.Ten = string.Concat(Enumerable.Repeat("--", g.Level)) + " " + g.Ten);
    var lstchucvu = (List<tbl_ChucVu>)TempData["chucvu"];
}
@using Web.Areas.Admin.Controllers
@model Web.Model.tbl_User
<script src="/Scripts/jquery.validate.min.js"></script>
<div class="panel panel-color panel-primary panel-pages" style="box-shadow: 1px 30px 48px 5px rgba(142, 142, 142, 0.71); ">
    <div class="panel-heading bg-img toplogin">
        <img src="/Content/Admin/images/logo.png" />
        <h3 class="text-center m-t-10 text-white">@ConfigTextController.GetValueCFT("register_taomoi") <br> @ConfigTextController.GetValueCFT("login_title")</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Register", "User", FormMethod.Post, new { id = "frmDKThanhVien", @class = "form-horizontal" }))
        {
            if (ViewBag.existUser == 1)
            {
                <div class="form-group">
                    <div class="col-xs-12 text-danger">Tên đăng nhập đã tồn tại !</div>
                </div>
            }
            <div class="form-group ">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.UserName, new { @class = "form-control input-lg", required = "", placeholder = @ConfigTextController.GetValueCFT("tendangnhap") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.PasswordFor(g => g.Password, new { @class = "form-control input-lg", required = "", placeholder = @ConfigTextController.GetValueCFT("matkhau") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.FullName, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("lienhe_hovaten") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Email, new { @class = "form-control input-lg", type = "email", required = "", placeholder = @ConfigTextController.GetValueCFT("lienhe_email") })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                   @Html.DropDownListFor(x => x.DonviId, new SelectList(lstdonvi, "Id", "Ten"), "--"+@ConfigTextController.GetValueCFT("register_donvi")+"--", new { @class = "form-control input-lg" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.DropDownListFor(x => x.ChucVuId, new SelectList(lstchucvu, "ID", "Name"), "--"+@ConfigTextController.GetValueCFT("register_chucvu")+"--", new { @class = "form-control input-lg" })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Telephone, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("register_dtban") })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-xs-12">
                    @Html.TextBoxFor(g => g.Phone, new { @class = "form-control input-lg", placeholder = @ConfigTextController.GetValueCFT("register_sodd") })
                </div>
            </div>
            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <button class="btn btn-primary waves-effect waves-light btn-lg w-lg submitbtn" type="submit">@ConfigTextController.GetValueCFT("register")</button>
                </div>
            </div>

            <div class="form-group m-t-30">
                <div class="col-sm-12 text-center">
                    @Html.ActionLink(@ConfigTextController.GetValueCFT("register_exist"), "Login")
                </div>
            </div>
        }
    </div>
</div>
<script>
    // Basic Form
    $(document).ready(function () {
        $.validator.addMethod("regex", function (value, element, regexpr) {
            return regexpr.test(value);
        }, "Please enter a valid pasword.");
        $("#frmDKThanhVien").validate({
            rules:
            {
                UserName:
                {
                    required: true,
                    regex: /^[a-zA-Z0-9_-]+$/
                },
                Password:
                {
                    required: true,
                    minlength: 6,
                },
                FullName:
                {
                    required: true
                },
                Email:
                {
                    email: true,
                    required: true
                },
                Phone:
                {
                    required: true,
                    minlength: 10,
                    maxlength: 14,
                },
            },
            messages:
            {
                UserName:
                {
                    required: "@ConfigTextController.GetValueCFT("register_validten")",
                    regex: "@ConfigTextController.GetValueCFT("register_regexUserName")"
                },
                Password:
                {
                    required: "@ConfigTextController.GetValueCFT("pass_validpass")",
                    minlength: "@ConfigTextController.GetValueCFT("pass_minlength")"
                },
                FullName:
                {
                    required: "@ConfigTextController.GetValueCFT("edit_validatehoten")"
                },
                Email:
                {
                    email: "@ConfigTextController.GetValueCFT("lienhe_validatEmail")",
                    required: "@ConfigTextController.GetValueCFT("register_validemail")"
                },
                Phone: {
                    required: "@ConfigTextController.GetValueCFT("register_validphone")",
                    minlength: "@ConfigTextController.GetValueCFT("register_validphonemin")",
                    maxlength: "@ConfigTextController.GetValueCFT("register_validphonemax")",
                }
            }
        });
    });
</script>
<style>
    label {
        font-weight: normal;
    }
</style>