Web/Areas/Admin/Controllers/LogoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.BaseSecurity;
using Web.Controllers;
using Web.Core;
using Web.Model;
using Web.Model.CustomModel;
using Web.Repository;
using Web.Repository.Entity;

namespace Web.Areas.Admin.Controllers
{
    public class LogoController : BaseController
    {
        readonly ILogoRepository logoRepository = new LogoRepository();
        const string Keycache = "keyadminmenu";
        //
        // GET: /AdminMenu/
        [Authorize(Roles = "Index")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Index")]
        public ActionResult ListData()
        {
            var lstLogo = logoRepository.GetAll();         
            return Json(new
            {
                viewContent = RenderViewToString("~/Areas/Admin/Views/Logo/_ListData.cshtml", lstLogo),
            }, JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Add")]
        public ActionResult Add()
        {
            return Json(RenderViewToString("~/Areas/Admin/Views/Logo/_Create.cshtml"), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Add")]
        [HttpPost]
        public ActionResult Add(Logo obj)
        {
            try
            {
                if (string.IsNullOrEmpty(obj.Image))
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Vui lòng thêm ảnh",
                    }, JsonRequestBehavior.AllowGet);
                }
                var logo = logoRepository.GetAll().FirstOrDefault(x => x.Name.Trim() == obj.Name.Trim());
                if (logo != null)
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Tên logo đã tồn tại",
                    }, JsonRequestBehavior.AllowGet);
                }
                logoRepository.Add(obj);
                HelperCache.RemoveCache(Keycache);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Thêm mới thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Thêm mới thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }
        [Authorize(Roles = "Edit")]
        public ActionResult Edit(int id)
        {
            var logo = logoRepository.Find(id);
            return Json(RenderViewToString("~/Areas/Admin/Views/Logo/_Edit.cshtml", logo), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Edit")]
        [HttpPost]
        public ActionResult Edit(Logo obj)
        {
            try
            {
                if (string.IsNullOrEmpty(obj.Image))
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Vui lòng thêm ảnh",
                    }, JsonRequestBehavior.AllowGet);
                }
                var logo = logoRepository.GetAll().FirstOrDefault(x => x.Name.Trim() == obj.Name.Trim() && x.ID != obj.ID);
                if (logo != null)
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Tên logo đã tồn tại",
                    }, JsonRequestBehavior.AllowGet);
                }
                logoRepository.Edit(obj);
                
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Cập nhật thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Cập nhật thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Delete")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                logoRepository.Delete(id);
                HelperCache.RemoveCache(Keycache);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Xóa menu thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Xóa menu thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
           
        }
       
        public ActionResult Active(int id,int active)
        {
            try
            {
                bool status = false;
                if (active == 1)
                    status = true;
                logoRepository.Active(id, status);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Cập nhật thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Cập nhật thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }
        
    }
}

Web/Areas/Admin/Views/Logo/Index.cshtml
@{
    ViewBag.Title = "Quản lý logo";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var lstAction = (List<int>)HttpContext.Current.Session["Action"];
}
@using Web.Model.CustomModel
@model List<Web.Model.Logo>
<script src="~/AppJs/logo.js"></script>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Quản lý Logo</h3>
                <div style="top: 8px;position: absolute; right: 40px;" class="pull-right">
                    @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Add))
                    {
                        <button type="button" class="btn btn-primary waves-effect waves-light" onclick="Logo.loadfrmAdd() "><i class="fa fa-plus"></i> Thêm mới</button>
                    }
                    
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="table-responsive" id="gridData">

                        </div>
                        <div class="col-md-12" id="paginationholder">
                            <ul id="pagination" class="pagination"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 

Web/Areas/Admin/Views/Logo/_Create.cshtml
 
@model Web.Model.Logo
@using (Ajax.BeginForm("Add", "Logo", null,
    new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "Logo.onAddSuccess"
    },
    new { @id = "basicForm", @class = "form-horizontal" }))
{
    <div class="form-group">
        <label class="col-md-2 control-label">Tên logo <span class="asterisk"> (*)</span></label>
        <div class="col-md-8">
            @Html.TextBoxFor(g => g.Name, new { @class = "form-control", placeholder = "Tên logo" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Hình ảnh <span class="asterisk"> (*)</span></label>
        <div class="col-md-8">
            @{ Html.RenderAction("UploadImage", "UploadFile", new { controlName = "Image" });}
            <img src="" id="prevImages">
            <span class="error" id="spImg"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Vị trí</label>
        <div class="col-md-3">
            <select class="form-control" name="Type" id="Type">
                <option value="1">Đầu trang</option>
                <option value="2">Cuối trang</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 pull-right">
            <div class="checkbox checkbox-primary">
                <input id="Status" name="Status" type="checkbox" checked="" value="true">
                <label for="Status">
                    Kích hoạt
                </label>
            </div>
        </div>
    </div>
    <div class="text-center">
        <button type="submit" id="btnAdd" class="btn btn-primary waves-effect waves-light">Thêm mới</button>
    </div>
}
<script>
    // Basic Form
    $(document).ready(function () {
        $('#btnAdd').click(function () {
            $(this).hide();
        })
        $('.form-control').on('click', function () {
            $('#btnAdd').show();
        })
        $("#basicForm").validate({
            rules:
        {
            Name:
            {
                required: true
            } 
        },
            messages:
            {
                Name:
                {
                    required: "Chưa nhập tên menu"
                } 
            }
        });
    });
</script>

Web/Areas/Admin/Views/Logo/_Edit.cshtml
@model Web.Model.Logo
@using (Ajax.BeginForm("Edit", "Logo", null,
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "Logo.onEditSuccess"
                },
                new { @id = "basicForm", @class = "form-horizontal" }))
{
    @Html.HiddenFor(x=>x.ID)
    <div class="form-group">
        <label class="col-md-2 control-label">Tên logo <span class="asterisk"> (*)</span></label>
        <div class="col-md-8">
            @Html.TextBoxFor(g => g.Name, new { @class = "form-control", placeholder = "Tên logo" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Hình ảnh <span class="asterisk"> (*)</span></label>
        <div class="col-md-8">
            @{ Html.RenderAction("UploadImage", "UploadFile", new { controlName = "Image" });}
            <img src="@Model.Image" style="width:100px" id="prevImages">
            <span class="error" id="spImg"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Vị trí</label>
        <div class="col-md-3">
            <select class="form-control" name="Type" id="Type">
                <option value="1">Đầu trang</option>
                <option value="2">Cuối trang</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 pull-right">
            <div class="checkbox checkbox-primary">
                <input id="Status" name="Status" type="checkbox" checked="" value="true">
                <label for="Status">
                    Kích hoạt
                </label>
            </div>
        </div>
    </div>
    <div class="text-center">
        <button type="submit" id="btnAdd" class="btn btn-primary waves-effect waves-light">Cập nhật</button>
    </div>
                }
<script>
    // Basic Form
    $(document).ready(function () {
        $('#Type').val(@Model.Type);
        $('#btnAdd').click(function () {
            $(this).hide();
        })
        $('.form-control').on('click', function () {
            $('#btnAdd').show();
        })
        $("#basicForm").validate({
            rules:
        {
            Name:
            {
                required: true
            }
        },
            messages:
            {
                Name:
                {
                    required: "Chưa nhập tên menu"
                }
            }
        });
    });
</script>

Web/Areas/Admin/Views/Logo/_ListData.cshtml
@{
    var lstAction = (List<int>)HttpContext.Current.Session["Action"];
}
@using Web.Model.CustomModel
@model List<Web.Model.Logo>
<table class="table table-striped cabn_datatable">
    <thead>
        <tr>
            <th>
                <input type="hidden" id="hdfID" />
                <div class="checkbox">
                    <input id="chkall" type="checkbox">
                    <label for="chkall"></label>
                </div>
            </th>
            <th>Tên logo</th>
            <th>Ảnh</th>
            <th>Vị trí</th>
            <th>Trạng thái</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string status = string.Empty;
            if (item.Status)
            {
                status = "Vô hiệu";
            }else
            {
                status = "Kích hoạt";
            }
            <tr>
                <td style="vertical-align: middle;">
                    <div class="checkbox">
                        <input type="checkbox" value="@item.ID" id="chk'@item.ID'">
                        <label for="chk'@item.ID'"></label>
                    </div>
                </td>
                <td style="vertical-align: middle;">@item.Name</td>
                <td><img style="width:50px" src="@item.Image" /></td>
                <td style="vertical-align: middle;">@Html.Raw(item.Type == 1 ? "<span>Đầu trang</span>" : "<span>Cuối trang</span>")</td>
                <td style="vertical-align: middle;">@Html.Raw(item.Status == true ? "<span style='color:green'>Kích hoạt</span>" : "<span style='color:red'>Vô hiệu</span>")</td>
                <td style="vertical-align: middle;">
                    <div class="btn-list pull-right mr5">
                        @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Edit))
                        {
                            <a href="#" class="btn btn-primary btn-bordered" onclick="Logo.loadfrmEdit(@item.ID) "><i class="glyphicon glyphicon-pencil"></i></a>
                        }
                        @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Edit))
                        {
                            <a href="#" class="btn btn-success btn-bordered" onclick="Logo.active(@item.ID,'@status') " title="@status">
                                <i class="fa fa-power-off"></i>
                            </a>
                        }
                        @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Delete))
                        {
                            <a href="#" class="btn btn-danger btn-bordered" onclick="Logo.ondelete(@item.ID) ">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function() {
        InitClickCheckAllInTable("chkall", function(res) {
            $("#hdfID").val(res);
        });
        $('.cabn_datatable').dataTable(
            {
                "oLanguage": {
                    "sUrl": "/Content/Vietnamese.json"
                },
            }
        );
    });
</script>