Web/Areas/Admin/Controllers/HomeMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Web.BaseSecurity;
using Web.Core;
using Web.Model;
using Web.Repository;
using Web.Repository.Entity;

namespace Web.Areas.Admin.Controllers
{
    public class HomeMenuController : BaseController
    {
        readonly IHomeMenuRepository _homeMenuRepository = new HomeMenuRepository();
        //
        // GET: /Admin/HomeMenu/
        [Authorize(Roles = "Index")]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Index")]
        [HttpPost]
        public ActionResult ListData(int page)
        {
            var model = _homeMenuRepository.GetAll();
            var totalAdv = model.Count();
            return Json(new
            {
                viewContent = RenderViewToString("~/Areas/Admin/Views/HomeMenu/_ListData.cshtml", model),
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Index")]
        public ActionResult GetAllByLangCode(string LangCode)
        {
            LangCode = LangCode ?? Webconfig.LangCodeVn;
            var lstHomeMenu = _homeMenuRepository.GetAll().ToList();
            var lstLevel = Common.CreateLevel(lstHomeMenu.ToList());
            return Json(lstLevel, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Add")]
        public ActionResult Add()
        {
            TempData["MenuHome"] = _homeMenuRepository.GetAll().ToList();
            return Json(RenderViewToString("~/Areas/Admin/Views/HomeMenu/_Create.cshtml"), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Add")]
        [HttpPost]
        public ActionResult Add(HomeMenu obj)
        {
            try
            {
                var menu = _homeMenuRepository.GetAll().FirstOrDefault(x => x.Name.Trim() == obj.Name.Trim());
                if(menu != null)
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Tên menu đã tồn tại",
                    }, JsonRequestBehavior.AllowGet);
                }
                obj.CreatedDate = DateTime.Now;
                _homeMenuRepository.Add(obj);
                
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Thêm mới menu thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Thêm mới menu thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Edit")]
        public ActionResult Edit(int id)
        {
            TempData["MenuHome"] = _homeMenuRepository.GetAll().ToList();
            var objHomeMenu = _homeMenuRepository.Find(id);
            return Json(RenderViewToString("~/Areas/Admin/Views/HomeMenu/_Edit.cshtml", objHomeMenu), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Edit")]
        [HttpPost]
        public ActionResult Edit(HomeMenu obj)
        {
            try
           {
                var munuName = _homeMenuRepository.GetAll().FirstOrDefault(x => x.Name.Trim() == obj.Name.Trim() && x.ID != obj.ID);
                if(munuName!= null)
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = "Tên menu đã tồn tại",
                    }, JsonRequestBehavior.AllowGet);
                }
                _homeMenuRepository.Edit(obj);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Cập nhật menu thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Cập nhật menu thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }
        [Authorize(Roles = "Delete")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var obj = _homeMenuRepository.Find(id);
                _homeMenuRepository.Delete(id);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Xóa menu thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                IsSuccess = true,
                Messenger = "Xóa menu thành công",
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Delete")]
        [HttpPost]
        public ActionResult DeleteAll(string lstid)
        {
            var arrid = lstid.Split(',');
            var count = 0;
            foreach (var item in arrid)
            {
                try
                {
                    // xoa danhh muc
                    _homeMenuRepository.Delete(Convert.ToInt32(item));
                    count++;
                }
                catch (Exception)
                {
                    continue;
                }
            }
            return Json(new
            {
                Messenger = string.Format("Xóa thành công {0} menu", count),
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Edit")]
        [HttpPost]
        public ActionResult UpdatePosition(string value)
        {
            var arrValue = value.Split('|');
            foreach (var item in arrValue)
            {
                var id = item.Split(':')[0];
                var pos = item.Split(':')[1];
                var obj = _homeMenuRepository.Find(Convert.ToInt32(id));
                obj.Ordering = Convert.ToInt32(pos);
                try
                {
                    _homeMenuRepository.Edit(obj);
                }
                catch (Exception)
                {
                    return Json(new
                    {
                        IsSuccess = false,
                        Messenger = string.Format("Cập nhật vị trí thất bại")
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new
            {
                IsSuccess = true,
                Messenger = "Cập nhật vị trí thành công",
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Web/Areas/Admin/Views/HomeMenu/Index.cshtml
@{
    ViewBag.Title = "Quản lý menu trang chủ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var lstAction = (List<int>)HttpContext.Current.Session["Action"];
}

@using Web.Model
@using Web.Model.CustomModel
@model List<Web.Model.HomeMenu>
<script src="~/AppJs/homemenu.js"></script>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Quản lý Menu trang chủ</h3>
                <div style="top: 8px;position: absolute; right: 40px;" class="pull-right">
                    @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Add))
                    {
                        <button type="button" class="btn btn-primary waves-effect waves-light" onclick="homemenu.loadfrmAdd() "><i class="fa fa-plus"></i> Thêm mới</button>
                    }
                    @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Edit))
                    {
                        <button type="button" class="btn btn-success waves-effect waves-light" onclick="homemenu.onupdateposittion() "><i class="fa fa-refresh"></i> Cập nhật vị trí</button>
                    }
                    @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Delete))
                    {
                        <button type="button" class="btn btn-danger waves-effect waves-light" onclick="homemenu.onmultidelete() "><i class="fa fa-trash-o"></i> Xóa nhiều</button>
                    }
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="table-responsive" id="gridData">

                        </div>
                        @*<div class="col-md-12" id="paginationholder">
                            <ul id="pagination" class="pagination"></ul>
                        </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        homemenu.loadData(1);
    });
</script>

Web/Areas/Admin/Views/HomeMenu/_Create.cshtml
@using Web.Model
@{
    var lstMenu = (List<HomeMenu>)TempData["MenuHome"];
}
@helper RenderMenu(HomeMenu parent, List<HomeMenu> listfull)
{
var lstChilds = listfull.Where(g => g.ParentId == parent.ID);
    <option value="@parent.ID">@(new String('-', ((int)parent.Level - 1) * 2))@parent.Name</option>
foreach (var child in lstChilds)
{
        @RenderMenu(child, listfull);
    }
}
@model HomeMenu
@using (Ajax.BeginForm("Add", "HomeMenu", null,
    new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "homemenu.onAddSuccess"
    },
    new { @id = "frmData", @class = "form-horizontal" }))
{
    <div class="form-group">
        <label class="col-md-2 control-label">Tên menu <span class="asterisk"> (*)</span></label>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Nhập tên menu", onchange = "getLinkSeo()" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Menu cha</label>
        <div class="col-md-6">
            <select class="form-control" name="ParentId" id="selParentId">
                <option value="0">-- Chọn Menu cha --</option>
                @foreach (var parent in lstMenu.Where(g => g.ParentId == 0))
                {
                    @RenderMenu(parent, lstMenu);
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Đường dẫn</label>
        <div class="col-md-10">
            @Html.TextBoxFor(g => g.Link, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Icon </label>
        <div class="col-md-10">
            @Html.TextBoxFor(g => g.Icon, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Thứ tự <span class="asterisk"> (*)</span></label>
        <div class="col-sm-3 lockChar">
            @Html.TextBoxFor(g => g.Ordering, new { @class = "form-control", placeholder = "Thứ tự...", Value = "0" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary waves-effect waves-light">Thêm mới</button>
        </div>
    </div>
    @Html.HiddenFor(x => x.LinkSeo)
}
<script src="~/Scripts/common.js"></script>
<script>   
    function getLinkSeo() {
        let name = $('#Name').val();
        $('#LinkSeo').val(RemoveMarkStr(name));
    }
    $(document).ready(function () {
        $('.lockChar').on("keypress", function () {
            return event.charCode >= 48 && event.charCode <= 57
        })
        $("#frmData").validate({
            rules:
            {
                Name:
                {
                    required: true,
                    maxlength: 250
                }
                ,
                DisplayOrder:
                {
                    required: true
                }
            },
            messages:
            {
                Name:
                {
                    required: "Vui lòng nhập tên menu"
                }
                ,
                DisplayOrder:
                {
                    required: "Vui lòng nhập thứ tự"
                }
            },
            highlight: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
</script>

Web/Areas/Admin/Views/HomeMenu/_Edit.cshtml
@using Web.Model
@model HomeMenu
@{
    var lstMenu = (List<HomeMenu>)TempData["MenuHome"];
}
@helper RenderMenu(HomeMenu parent, List<HomeMenu> listfull)
{
var lstChilds = listfull.Where(g => g.ParentId == parent.ID);
    <option value="@parent.ID">@(new String('-', ((int)parent.Level - 1) * 2))@parent.Name</option>
foreach (var child in lstChilds)
{
        @RenderMenu(child, listfull);
    }
}
@using (Ajax.BeginForm("Edit", "HomeMenu", null,
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "homemenu.onEditSuccess"
                },
                new { @id = "frmData", @class = "form-horizontal" }))
{
    @Html.HiddenFor(x=>x.ID)
    <div class="form-group">
        <label class="col-md-2 control-label">Tên menu</label>
        <div class="col-md-10">
          @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Nhập tên menu", onchange = "getLinkSeo()"})
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Menu cha</label>
        <div class="col-md-6">
            <select class="form-control" name="ParentId" id="selParentId">
                <option value="0">--Chọn Menu cha--</option>
                @foreach (var parent in lstMenu.Where(g => g.ParentId == 0))
                {
                    @RenderMenu(parent, lstMenu);
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Đường dẫn</label>
        <div class="col-md-10">
            @Html.TextBoxFor(g => g.Link, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Icon </label>
        <div class="col-md-10">
            @Html.TextBoxFor(g => g.Icon, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Thứ tự</label>
        <div class="col-sm-3">
            @Html.TextBoxFor(g => g.Ordering, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary waves-effect waves-light">Cập nhật</button>
        </div>
    </div>
}
<script src="~/Scripts/common.js"></script>
<script>
    function getLinkSeo() {
        let name = $('#Name').val();
        $('#LinkSeo').val(RemoveMarkStr(name));
    }
    $(document).ready(function () {
        $("#frmData").validate({
            rules:
            {
                Name:
                {
                    required: true,
                    maxlength: 250
                }
                ,
                DisplayOrder:
                {
                    required: true
                }
            },
            messages:
            {
                Name:
                {
                    required: "Vui lòng nhập tên menu"
                }
                ,
                DisplayOrder:
                {
                    required: "Vui lòng nhập thứ tự"
                }
            },
            highlight: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
</script>

Web/Areas/Admin/Views/HomeMenu/_ListData.cshtml
@{
    var lstAction = (List<int>)HttpContext.Current.Session["Action"];
}
@using Web.Model.CustomModel
@model List<Web.Model.HomeMenu>
<table class="table table-striped cabn_datatable">
    <thead>
        <tr>
            <th>
                <input type="hidden" id="hdfID" />
                <div class="checkbox">
                    <input id="chkall" type="checkbox">
                    <label for="chkall"></label>
                </div>
            </th>
            <th>Tên menu</th>
            <th>LinkSeo</th>
            <th>Icon</th>
            <th>Thứ tự</th>
            <th>Ngày tạo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="vertical-align: middle;">
                    <div class="checkbox">
                        <input type="checkbox" value="@item.ID" id="chk'@item.ID'">
                        <label for="chk'@item.ID'"></label>
                    </div>
                </td>
                <td style="vertical-align: middle;">@item.Name</td>
                <td style="vertical-align: middle;">@item.Link</td>
                <td style="vertical-align: middle;">@item.Icon</td>
                <td style="vertical-align: middle;">
                    @Html.HiddenFor(g => item.ID,new { @class= "item_ID" })
                    @Html.TextBoxFor(g => item.Ordering, new { @class = "form-control width50 text-center" })
                </td>
                <td>@string.Format("{0:dd/MM/yyyy HH:mm}", item.CreatedDate)</td>
                <td>
                    <div class="btn-list pull-right mr5">
                        @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Edit))
                        {
                            <a href="#" class="btn btn-primary btn-bordered" onclick="homemenu.loadfrmedit(@item.ID) " title="Sửa"><i class="glyphicon glyphicon-pencil"></i></a>
                        }
                        @if (lstAction != null && lstAction.Contains((int)EnumHelper.Action.Delete))
                        {
                            <a href="#" class="btn btn-danger btn-bordered" onclick="homemenu.ondelete(@item.ID) " title="Xóa">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('.width50').on("keypress", function () {
            return event.charCode >= 48 && event.charCode <= 57
        })
        InitClickCheckAllInTable("chkall", function (res) {
            $("#hdfID").val(res);
        });
        $('.cabn_datatable').dataTable(
          {
              "oLanguage": {
                  "sUrl": "/Content/Vietnamese.json"
              },
          }
      );
    });
</script>