Web/Areas/Admin/Controllers/InstructionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.BaseSecurity;
using Web.Model;
using Web.Repository;
using Web.Repository.Entity;

namespace Web.Areas.Admin.Controllers
{
    public class InstructionController : BaseController
    {
        //
        // GET: /Admin/Instruction/
        readonly IInstructionRepository _instructionRepository = new InstructionRepository();
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Index")]
        [HttpPost]
        public ActionResult ListData()
        {
            var lstObj = _instructionRepository.GetAll().ToList();
            return Json(new
            {
                viewContent = RenderViewToString("~/Areas/Admin/Views/Instruction/_ListData.cshtml", lstObj),
            }, JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Add")]
        public ActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "Add")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Instruction obj)
        {
            try
            {
                obj.CreatedDate = DateTime.Now;
                _instructionRepository.Add(obj);
               
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Thêm mới thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Thêm mới thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int id)
        {
            var obj = _instructionRepository.Find(id);
            return View(obj);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Instruction obj)
        {
            try
            {
               
                _instructionRepository.Edit(obj);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Cập nhật thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Cập thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                _instructionRepository.Delete(id);
                return Json(new
                {
                    IsSuccess = true,
                    Messenger = "Xóa thành công",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    IsSuccess = false,
                    Messenger = string.Format("Xóa thất bại")
                }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Detail(int id)
        {
            var obj = _instructionRepository.Find(id);
            return Json(RenderViewToString("~/Areas/Admin/Views/Instruction/Detail.cshtml", obj), JsonRequestBehavior.AllowGet);
        }
    }
}

Web/Controllers/InstructionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.BaseSecurity;
using Web.Model;
using Web.Repository;
using Web.Repository.Entity;

namespace Web.Controllers
{
    public class InstructionController : Controller
    {
        IInstructionRepository instructionRepository = new InstructionRepository();
        // GET: News
        public ActionResult Index()
        {
            var obj = instructionRepository.GetAll().FirstOrDefault();
            return View(obj);
        }
    }
}

Web/Areas/Admin/Views/Instruction/Add.cshtml
@using Web.Model
@model  Instruction
@{ 
    ViewBag.Title = "Thêm hướng dẫn mua hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    
}
<script src="~/AppJs/instruction.js"></script>
@using (Ajax.BeginForm("Add", "Instruction", null,
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "instruction.onAddSuccess"
                },
                new { @id = "frmData", @class = "form-horizontal" }))
{
    <input type="hidden" name="close" id="close" value="" />
    <div class="form-group">
        <label class="control-label col-md-2">Tiêu đề<span class="asterisk"> (*)</span></label>
        <div class="col-md-6">
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Mô tả ngắn</label>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Nội dung<span class="asterisk"> (*)</span></label>
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Contents, new { @class = "form-control", @rows = "7" })
            <span  class="error" id="spcontent"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <a  href="/Admin/Instruction" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Quay trở lại</a>
            <button type="submit"  onclick="checkAdd('close')" id="btnsaveadd" class="btn btn-primary">Thêm mới</button>
        </div>
    </div>
   }
<script src="~/Content/plugins/jquery-tag-it/js/jquery-ui.min.js"></script>
<script src="~/Content/plugins/ckeditor/ckeditor.js"></script>
<script src="~/Content/plugins/ckfinder/ckfinder.js"></script>
<script>
    $(document).ready(function () {
        $('#fileUpload').on('change', function () {
            $('#spImg').text("");
        })
       
        $("#frmData").validate({
            rules:
            {
               Title:
                {
                    required: true,
                    maxlength: 500
                }
            },
            messages:
            {
                Title:
                {
                    required: "Vui lòng nhập tiêu đề"
                }
            },
            highlight: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-error');
            }
        });
    })
    var editor = CKEDITOR.replace('Contents', {
        height: '350px',
        startupFocus: true,
        language: 'vi',
        filebrowserBrowseUrl: "/Content/plugins/ckfinder/ckfinder.html",
        filebrowserImageBrowseUrl: '/Content/plugins/ckfinder/ckfinder.html?Type=Images',
        filebrowserFlashBrowseUrl: '/Content/plugins/ckfinder/ckfinder.html?Type=Flash',
        filebrowserUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Flash'
    });
    editor.on('change', function () {
        $("#spcontent").text('');
    })
    function getUrl() {
        let status = $('#Status').val();
        let url = "/admin/news?status=" + status
        $('#backNews').attr("href", url)
    }
  
    function checkAdd(state) {
        $('#close').val(state);
        var messageLength = CKEDITOR.instances['Contents'].getData().replace(/<[^>]*>/gi, '').length;
        if (!messageLength) {
            $("#spcontent").text("Vui lòng thêm nội dung bài viết");
            return false;
        }
    }

</script>

Web/Areas/Admin/Views/Instruction/Detail.cshtml
@model Web.Model.Instruction

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-md-2 control-label">Tiêu đề:</label>
        <div class="col-md-10">
            <p style="margin-top:7px">@Model.Title</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Mô tả:</label>
        <div class="col-md-10">
            <p style="margin-top:7px">@Model.Description</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Nội dung:</label>
        <div id="detail" class="col-sm-10">
            <p>@Html.Raw(Model.Contents)</p>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/Instruction/Edit.cshtml
@using Web.Model
@model  Instruction
@{
    ViewBag.Title = "Thêm hướng dẫn mua hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}
<script src="~/AppJs/instruction.js"></script>
@using (Ajax.BeginForm("Edit", "Instruction", null,
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                OnSuccess = "instruction.onEditSuccess"
                            },
                            new { @id = "frmData", @class = "form-horizontal" }))
{
    @Html.HiddenFor(x => x.ID);
    @Html.HiddenFor(x => x.CreatedDate);
    <input type="hidden" name="close" id="close" value="" />
    <div class="form-group">
        <label class="control-label col-md-2">Tiêu đề<span class="asterisk"> (*)</span></label>
        <div class="col-md-6">
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Mô tả ngắn</label>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Nội dung<span class="asterisk"> (*)</span></label>
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Contents, new { @class = "form-control",@rows="7" })
            <span class="error" id="spcontent"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <a href="/Admin/Instruction" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Quay trở lại</a>
            <button type="submit" onclick="checkAdd('close')" id="btnsaveadd" class="btn btn-primary">Lưu lại</button>
        </div>
    </div>
                    }
<script src="~/Content/plugins/jquery-tag-it/js/jquery-ui.min.js"></script>
<script src="~/Content/plugins/ckeditor/ckeditor.js"></script>
<script src="~/Content/plugins/ckfinder/ckfinder.js"></script>
<script>
    $(document).ready(function () {
        $('#fileUpload').on('change', function () {
            $('#spImg').text("");
        })

        $("#frmData").validate({
            rules:
            {
               Title:
                {
                    required: true,
                    maxlength: 500
                }
            },
            messages:
            {
                Title:
                {
                    required: "Vui lòng nhập tiêu đề"
                }
            },
            highlight: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                jQuery(element).closest('.form-group').removeClass('has-error');
            }
        });
    })
    var editor = CKEDITOR.replace('Contents', {
        height: '350px',
        startupFocus: true,
        language: 'vi',
        filebrowserBrowseUrl: "/Content/plugins/ckfinder/ckfinder.html",
        filebrowserImageBrowseUrl: '/Content/plugins/ckfinder/ckfinder.html?Type=Images',
        filebrowserFlashBrowseUrl: '/Content/plugins/ckfinder/ckfinder.html?Type=Flash',
        filebrowserUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl: '/Scripts/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Flash'
    });
    editor.on('change', function () {
        $("#spcontent").text('');
    })
    function getUrl() {
        let status = $('#Status').val();
        let url = "/admin/news?status=" + status
        $('#backNews').attr("href", url)
    }

    function checkAdd(state) {
        $('#close').val(state);
        var messageLength = CKEDITOR.instances['Contents'].getData().replace(/<[^>]*>/gi, '').length;
        if (!messageLength) {
            $("#spcontent").text("Vui lòng thêm nội dung bài viết");
            return false;
        }
    }

</script>

Web/Areas/Admin/Views/Instruction/Index.cshtml
@{
    ViewBag.Title = "Hướng dẫn mua hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/AppJs/instruction.js"></script>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Hướng dẫn mua hàng </h3>
                <div style="top: 8px;position: absolute; right: 40px;" class="pull-right">
                    <a type="button" class="btn btn-primary waves-effect waves-light" href="/Admin/Instruction/Add"><i class="fa fa-plus"></i> Thêm mới</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="table-responsive" id="gridData">

                        </div>
                        <div class="pull-right" id="paginationholder">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/Instruction/_ListData.cshtml
@using Web.Model.CustomModel
@model IEnumerable<Web.Model.Instruction>
 @using Web.Core
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Tiêu đề</th>
            <th>Mô tả</th>
            <th>Nội dung</th>
            <th>Ngày tạo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@HelperString.TruncateByWord(HelperString.StripHTML(HttpUtility.HtmlDecode(item.Description)), 120)</td>
                <td>@HelperString.TruncateByWord(HelperString.StripHTML(HttpUtility.HtmlDecode(item.Contents)), 120)</td>
                <td>@string.Format("{0:dd/MM/yyyy HH:mm}", item.CreatedDate)</td>
                <td  style="width:150px">
                    <div class="btn-list pull-right mr5">
                        <a href="#" class="btn btn-danger btn-bordered" onclick="instruction.loadfrmDetail(@item.ID)">
                            <i class="glyphicon glyphicon-info-sign"></i>
                        </a>
                            <a href="/Admin/Instruction/Edit/@item.ID" class="btn btn-primary btn-bordered" >
                                <i class="glyphicon glyphicon-pencil"></i></a>
                            <a href="#" class="btn btn-danger btn-bordered" onclick="instruction.ondelete(@item.ID)">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>